### ISSUE TITLE
Add CURVE support

### ISSUE THREAD

**Issue by trevorbernard** [zeromq/jzmq#272]

**Comment by blair-anson** [comment]
@trevorbernard did you get any further with supporting Curve via JNI?

**Comment by djelenc** [comment]
Recent updates ([PR#388](https://github.com/zeromq/jzmq/pull/388), [PR#392](https://github.com/zeromq/jzmq/pull/392)) address curve security. I'd say that curve via JNI is now fully supported.

**Comment by trevorbernard** [comment]
@djelenc awesome
