### ISSUE TITLE
CMake fails to find JNI - Missing JAVA_JVM_LIBRARY (Windows 8.1)

### ISSUE THREAD

**Issue by TwistaWare** [zeromq/jzmq#332]
New installation of Cmake & Java 1.7.0.60

In the example you show:
    Found JNI: C:/Program Files/Java/jdk1.6.0_27/lib/jawt.lib

And this file is in that location on my system.

Here is the output:-

c:\Users\pmjw.CORENEUL\Downloads\jzmq-master\build64>cmake .. -G "NMake Makefiles"
-- The C compiler identification is MSVC 17.0.60610.1
-- The CXX compiler identification is MSVC 17.0.60610.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 11.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 11.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 11.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 11.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Java: C:/Program Files/Java/jdk1.7.0_60/bin/java.exe (found version "1.7.0.60")
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find JNI (missing: JAVA_JVM_LIBRARY)
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files (x86)/CMake/share/cmake-3.0/Modules/FindJNI.cmake:286 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:7 (find_package)

-- Configuring incomplete, errors occurred!
See also "C:/Users/pmjw.CORENEUL/Downloads/jzmq-master/build64/CMakeFiles/CMakeOutput.log".

I can't seem to find how to resolve this. everything looks ok on my system.

**Comment by tobegit3hub** [comment]
You can ignore this libraries if not used.

```
set(JAVA_AWT_LIBRARY NotNeeded)
set(JAVA_JVM_LIBRARY NotNeeded)
set(JAVA_INCLUDE_PATH2 NotNeeded)
set(JAVA_AWT_INCLUDE_PATH NotNeeded)
find_package(JNI REQUIRED)
```
