### ISSUE TITLE
Can't exec "libtoolize": No such file or directory at /usr/local/share/autoconf/

### ISSUE THREAD

**Issue by jnuc093** [zeromq/jzmq#365]
➜  jzmq git:(master) ./autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.in: not using Gettext
autoreconf: running: aclocal -I config --force -I config
aclocal: warning: autoconf input should be named 'configure.ac', not 'configure.in'
autoreconf: configure.in: tracing
autoreconf: running: libtoolize --copy --force
Can't exec "libtoolize": No such file or directory at /usr/local/share/autoconf/Autom4te/FileUtils.pm line 345, <GEN3> line 6.
autoreconf: failed to run libtoolize: No such file or directory
autoreconf: libtoolize is needed because this package uses Libtool
autogen.sh: error: autoreconf exited with status 0

how can i install jzmq on osx10.9

**Comment by utgarda** [comment]
@jnuc093 you probably need to install libtool and libtool-bin
For Ubuntu Linux use the following line: `apt-get install libtool libtool-bin`
On osx you could try something like this: http://munchpress.com/installing-autoconf-automake-libtool-on-mac-osx-mountain-lion/
