### ISSUE TITLE
CTX.Socket.recv is a public method marked final, and prevents mocking

### ISSUE THREAD

**Issue by Ghoughpteighbteau** [zeromq/jzmq#370]
https://github.com/zeromq/jzmq/blob/master/src/main/java/org/zeromq/ZMQ.java#L1647

we're trying to write some unit tests by mocking out socket and passing our own results in, we're blocked by the fact that recv is final.

I'm not sure of the rational to make this (or any method) final, so I'm requesting that it not be.

**Comment by sjohnr** [comment]
Good idea. Can't say I can answer your question (implied?). But, can you change it and/or some of the other methods and submit a pull request?

**Comment by Ghoughpteighbteau** [comment]
cool man! Saved me from submitting. @trevorbernard  Would you mind if I do the same thing to JeroMQ as well? We have other projects that depend on that one as well.
