### ISSUE TITLE
ZMQ.cpp:23:28: fatal error: org_zeromq_ZMQ.h: No such file or directory  #include "org_zeromq_ZMQ.h"

### ISSUE THREAD

**Issue by NSjogren** [zeromq/jzmq#375]
When trying to build with the latest commit (a4f10672e57d1a4b01cdc5364e336a47fd04d9e1) I get this. 

ZMQ.cpp:23:28: fatal error: org_zeromq_ZMQ.h: No such file or directory  #include "org_zeromq_ZMQ.h"

Ubuntu 14.04, works with older commits however.

**Comment by balsukrishna** [comment]
Hi,
Yes. I also faced same issue when building latest commit on ubuntu 14.04.

**Comment by NSjogren** [comment]
Worked when using ./configure --with-zeromq=/usr/local

**Comment by trevorbernard** [comment]
This issue is resolved by e9b699afdfeeadf5c07dfd68831ba5b6b5c0a66b
