### ISSUE TITLE
Native Library /usr/local/lib/libjzmq.so.0.0.0 already loaded in another classloader

### ISSUE THREAD

**Issue by rominavarela** [zeromq/jzmq#394]
I have two web apps in spring, both ussing the pom dependecy:

 > \<dependency\>
 > 	    \<groupId\>org.zeromq\</groupId\>
 >	    \<artifactId\>jzmq\</artifactId\>
 >		\<version\>3.1.0\</version\>
 >   \</dependency\>

The webapps are deployed together in tomcat and the message is thrown for the second one:

    java.lang.UnsatisfiedLinkError: Native Library /usr/local/lib/libjzmq.so.0.0.0 already loaded in another classloader

This issue is related to the closed thread https://github.com/zeromq/jzmq/issues/22 

* Quote:

    can you check if the lib is loaded and load only if it's not?

    I mean the code:
    static {
    System.loadLibrary ("jzmq");
    }

**Comment by trevorbernard** [comment]
As you've encountered, you cannot load multiple versions of the same native library. My suggestion would be to look at your web containers FAQ regarding classloaders and JNI. Typically the way around this is to place the native library in a shared folder used by the container.

**Comment by jivk** [comment]
I too am seeing the issue but in Unit Tests.  I'm not really sure how to apply the above solution in my context though.
