### ISSUE TITLE
Compatibility jzmq with zmq releases

### ISSUE THREAD

**Issue by jaapdejong** [zeromq/jzmq#396]
Hi All!

just wondering what releases from jzmq match with which zmq release.
Is there a relation at all?

And the second, more important question: what jzmq release matches with the most recent zmq 4.1.3 version.
Should I use the most recent commit?
Will there be a new release of jzmq soon? 
Would prefer a release instead...

Thanks!
Jaap

**Comment by trevorbernard** [comment]
@jaapdejong,

JZMQ is designed to be backwards compatible with multiple versions of libzmq. I would suggest using the latest stable version or the latest master.

> Will there be a new release of jzmq soon?

We are long overdue for a new stable release. Hopefully, we'll get to it sooner rather than later.

**Comment by jaapdejong** [comment]
@trevorbernard 
Thanks!
