### ISSUE TITLE
Problem: The project does not explicitly define its collaboration process

### ISSUE THREAD

**Issue by msteinhoff** [zeromq/jzmq#418]
@zeromq/jzmq-administrators I assume that jzmq also uses C4.1?

**Comment by trevorbernard** [comment]
Yes

**Comment by msteinhoff** [comment]
Ok.

Hint to my lazy self: Steal [CONTRIBUTING.md](https://github.com/zeromq/czmq/blob/master/CONTRIBUTING.md) from czmq.
