### ISSUE TITLE
Exposing get/setsockopt methods as public members [improvement]

### ISSUE THREAD

**Issue by sjlnk** [zeromq/jzmq#438]
I'm expanding cljzmq bindings functionality (integration with core.async) and I'd like a simple way to set socket options without using one of the numerous methods written for that reason.

It would be great to have a public access to these `native` methods:
- org.zeromq.ZMQ.getLongSockopt
- org.zeromq.ZMQ.getBytesSockopt
- org.zeromq.ZMQ.setLongSockopt
- org.zeromq.ZMQ.setBytesSockopt

Why have they been declared protected? Having a direct access would massively reduce code repetition in my case and it's not unsafe as long as those integer option types will stay the same. As far as I know the only way to access those now is by subclassing ZMQ, ZMQ.Context, ZMQ.Socket and ZContext objects. Accessing protected native members via reflection is not possible, it seems.

**Comment by jjbastian** [comment]
To reiterate why I think it would be a good idea to expose those members to public:
- Easy access for people that would benefit from them, especially for JVM based language binding development and testing purposes.
- Straightforward access to well documented functionality of libzmq without unnecessary convolutions for people that are very familiar with the underlying library but not necessary familiar with jzmq.
- Option numbering and value type (long or bytes) is bound to stay the same more or less indefinitely.
- Often new features are introduced to libzmq via socket options and those might not be available in jzmq as a public ZMQ.Socket wrapper yet. They would still be available to users if they were able to access those methods.

While protected access is following the principles of sane OOP, in this case it seems to be overly protective and prohibits many valid use cases power users might have.
