### ISSUE TITLE
What is the effective license for JZMQ?

### ISSUE THREAD

**Issue by jcoeltjen** [zeromq/jzmq#451]
This may be a dumb question but I am a little bit confused by the two COPYING files in the root folder.

Github shows that JZMQ is GPL but there is also the LGPL linked...

Is JZMQ GPL or LGPL? This is imported for me as I can't use JZMQ for work projects when it is using a GPL license.

**Comment by jimrthy** [comment]
I think it's probably the same as http://zeromq.org/area:faq#toc4.

But the mailing list would be a much better place to ask. Who knows what the rules are, based on the various authors who have contributed over the years.

Ultimately, you'll have to ask the lawyers.

**Comment by trevorbernard** [comment]
The license is LGPLv3 with a static link exception
